    #ifdef E2BIG
        [E2BIG] = "E2BIG",
    #endif
    #ifdef EACCES
        [EACCES] = "EACCES",
    #endif
    #ifdef EACTIVE
        [EACTIVE] = "EACTIVE",
    #endif
    #ifdef EADDRINUSE
        [EADDRINUSE] = "EADDRINUSE",
    #endif
    #ifdef EADDRNOTAVAIL
        [EADDRNOTAVAIL] = "EADDRNOTAVAIL",
    #endif
    #ifdef EADI
        [EADI] = "EADI",
    #endif
    #ifdef EADV
        [EADV] = "EADV",
    #endif
    #ifdef EAFNOSUPPORT
        [EAFNOSUPPORT] = "EAFNOSUPPORT",
    #endif
    #ifdef EAGAIN
        [EAGAIN] = "EAGAIN",
    #endif
    #ifdef EAIO
        [EAIO] = "EAIO",
    #endif
    #ifdef EAI_AGAIN
        [EAI_AGAIN] = "EAI_AGAIN",
    #endif
    #ifdef EAI_BADFLAGS
        [EAI_BADFLAGS] = "EAI_BADFLAGS",
    #endif
    #ifdef EAI_FAIL
        [EAI_FAIL] = "EAI_FAIL",
    #endif
    #ifdef EAI_FAMILY
        [EAI_FAMILY] = "EAI_FAMILY",
    #endif
    #ifdef EAI_MEMORY
        [EAI_MEMORY] = "EAI_MEMORY",
    #endif
    #ifdef EAI_NONAME
        [EAI_NONAME] = "EAI_NONAME",
    #endif
    #ifdef EAI_OVERFLOW
        [EAI_OVERFLOW] = "EAI_OVERFLOW",
    #endif
    #ifdef EAI_SERVICE
        [EAI_SERVICE] = "EAI_SERVICE",
    #endif
    #ifdef EAI_SOCKTYPE
        [EAI_SOCKTYPE] = "EAI_SOCKTYPE",
    #endif
    #ifdef EALIGN
        [EALIGN] = "EALIGN",
    #endif
    #ifdef EALREADY
        [EALREADY] = "EALREADY",
    #endif
    #ifdef EASYNC
        [EASYNC] = "EASYNC",
    #endif
    #ifdef EAUTH
        [EAUTH] = "EAUTH",
    #endif
    #ifdef EBACKGROUND
        [EBACKGROUND] = "EBACKGROUND",
    #endif
    #ifdef EBADARCH
        [EBADARCH] = "EBADARCH",
    #endif
    #ifdef EBADCALL
        [EBADCALL] = "EBADCALL",
    #endif
    #ifdef EBADCOOKIE
        [EBADCOOKIE] = "EBADCOOKIE",
    #endif
    #ifdef EBADCPU
        [EBADCPU] = "EBADCPU",
    #endif
    #ifdef EBADE
        [EBADE] = "EBADE",
    #endif
    #ifdef EBADEPT
        [EBADEPT] = "EBADEPT",
    #endif
    #ifdef EBADEXEC
        [EBADEXEC] = "EBADEXEC",
    #endif
    #ifdef EBADF
        [EBADF] = "EBADF",
    #endif
    #ifdef EBADFD
        [EBADFD] = "EBADFD",
    #endif
    #ifdef EBADFILT
        [EBADFILT] = "EBADFILT",
    #endif
    #ifdef EBADFSYS
        [EBADFSYS] = "EBADFSYS",
    #endif
    #ifdef EBADHANDLE
        [EBADHANDLE] = "EBADHANDLE",
    #endif
    #ifdef EBADIOCTL
        [EBADIOCTL] = "EBADIOCTL",
    #endif
    #ifdef EBADMACHO
        [EBADMACHO] = "EBADMACHO",
    #endif
    #ifdef EBADMODE
        [EBADMODE] = "EBADMODE",
    #endif
    #ifdef EBADMSG
        [EBADMSG] = "EBADMSG",
    #endif
    #ifdef EBADOBJ
        [EBADOBJ] = "EBADOBJ",
    #endif
    #ifdef EBADR
        [EBADR] = "EBADR",
    #endif
    #ifdef EBADREQUEST
        [EBADREQUEST] = "EBADREQUEST",
    #endif
    #ifdef EBADRPC
        [EBADRPC] = "EBADRPC",
    #endif
    #ifdef EBADRQC
        [EBADRQC] = "EBADRQC",
    #endif
    #ifdef EBADRSPEC
        [EBADRSPEC] = "EBADRSPEC",
    #endif
    #ifdef EBADSLT
        [EBADSLT] = "EBADSLT",
    #endif
    #ifdef EBADTSPEC
        [EBADTSPEC] = "EBADTSPEC",
    #endif
    #ifdef EBADTYPE
        [EBADTYPE] = "EBADTYPE",
    #endif
    #ifdef EBADVER
        [EBADVER] = "EBADVER",
    #endif
    #ifdef EBDHDL
        [EBDHDL] = "EBDHDL",
    #endif
    #ifdef EBFONT
        [EBFONT] = "EBFONT",
    #endif
    #ifdef EBUFSIZE
        [EBUFSIZE] = "EBUFSIZE",
    #endif
    #ifdef EBUSY
        [EBUSY] = "EBUSY",
    #endif
    #ifdef ECALLDENIED
        [ECALLDENIED] = "ECALLDENIED",
    #endif
    #ifdef ECANCEL
        [ECANCEL] = "ECANCEL",
    #endif
    #ifdef ECANCELED
        [ECANCELED] = "ECANCELED",
    #endif
    #ifdef ECANCELLED
        #if !defined(ECANCELED) || ECANCELLED != ECANCELED
        [ECANCELLED] = "ECANCELLED",
        #endif
    #endif
    #ifdef ECAPMODE
        [ECAPMODE] = "ECAPMODE",
    #endif
    #ifdef ECASECLASH
        [ECASECLASH] = "ECASECLASH",
    #endif
    #ifdef ECHILD
        [ECHILD] = "ECHILD",
    #endif
    #ifdef ECHRNG
        [ECHRNG] = "ECHRNG",
    #endif
    #ifdef ECKPT
        [ECKPT] = "ECKPT",
    #endif
    #ifdef ECKSUM
        [ECKSUM] = "ECKSUM",
    #endif
    #ifdef ECLONEME
        [ECLONEME] = "ECLONEME",
    #endif
    #ifdef ECLOSED
        [ECLOSED] = "ECLOSED",
    #endif
    #ifdef ECOMM
        [ECOMM] = "ECOMM",
    #endif
    #ifdef ECONFIG
        [ECONFIG] = "ECONFIG",
    #endif
    #ifdef ECONNABORTED
        [ECONNABORTED] = "ECONNABORTED",
    #endif
    #ifdef ECONNCLOSED
        [ECONNCLOSED] = "ECONNCLOSED",
    #endif
    #ifdef ECONNREFUSED
        [ECONNREFUSED] = "ECONNREFUSED",
    #endif
    #ifdef ECONNRESET
        [ECONNRESET] = "ECONNRESET",
    #endif
    #ifdef ECONSOLEINTERRUPT
        [ECONSOLEINTERRUPT] = "ECONSOLEINTERRUPT",
    #endif
    #ifdef ECORRUPT
        [ECORRUPT] = "ECORRUPT",
    #endif
    #ifdef ECTRLTERM
        [ECTRLTERM] = "ECTRLTERM",
    #endif
    #ifdef ECVCERORR
        [ECVCERORR] = "ECVCERORR",
    #endif
    #ifdef ECVPERORR
        [ECVPERORR] = "ECVPERORR",
    #endif
    #ifdef ED
        [ED] = "ED",
    #endif
    #ifdef EDATALESS
        [EDATALESS] = "EDATALESS",
    #endif
    #ifdef EDEADEPT
        [EDEADEPT] = "EDEADEPT",
    #endif
    #ifdef EDEADLK
        [EDEADLK] = "EDEADLK",
    #endif
    #ifdef EDEADLOCK
        #if !defined(EDEADLK) || EDEADLOCK != EDEADLK
        [EDEADLOCK] = "EDEADLOCK",
        #endif
    #endif
    #ifdef EDEADSRCDST
        [EDEADSRCDST] = "EDEADSRCDST",
    #endif
    #ifdef EDESTADDREQ
        #if !defined(EDESTADDRREQ) || EDESTADDREQ != EDESTADDRREQ
        [EDESTADDREQ] = "EDESTADDREQ",
        #endif
    #endif
    #ifdef EDESTADDRREQ
        [EDESTADDRREQ] = "EDESTADDRREQ",
    #endif
    #ifdef EDEVERR
        [EDEVERR] = "EDEVERR",
    #endif
    #ifdef EDIED
        [EDIED] = "EDIED",
    #endif
    #ifdef EDIRIOCTL
        [EDIRIOCTL] = "EDIRIOCTL",
    #endif
    #ifdef EDIRTY
        [EDIRTY] = "EDIRTY",
    #endif
    #ifdef EDIST
        [EDIST] = "EDIST",
    #endif
    #ifdef EDOM
        [EDOM] = "EDOM",
    #endif
    #ifdef EDOMAINSERVERFAILURE
        [EDOMAINSERVERFAILURE] = "EDOMAINSERVERFAILURE",
    #endif
    #ifdef EDONTREPLY
        [EDONTREPLY] = "EDONTREPLY",
    #endif
    #ifdef EDOOFUS
        [EDOOFUS] = "EDOOFUS",
    #endif
    #ifdef EDOTDOT
        [EDOTDOT] = "EDOTDOT",
    #endif
    #ifdef EDQUOT
        [EDQUOT] = "EDQUOT",
    #endif
    #ifdef EDUPBADOPCODE
        [EDUPBADOPCODE] = "EDUPBADOPCODE",
    #endif
    #ifdef EDUPFD
        [EDUPFD] = "EDUPFD",
    #endif
    #ifdef EDUPINTRANSIT
        [EDUPINTRANSIT] = "EDUPINTRANSIT",
    #endif
    #ifdef EDUPNOCONN
        [EDUPNOCONN] = "EDUPNOCONN",
    #endif
    #ifdef EDUPNODISCONN
        [EDUPNODISCONN] = "EDUPNODISCONN",
    #endif
    #ifdef EDUPNOTCNTD
        [EDUPNOTCNTD] = "EDUPNOTCNTD",
    #endif
    #ifdef EDUPNOTIDLE
        [EDUPNOTIDLE] = "EDUPNOTIDLE",
    #endif
    #ifdef EDUPNOTRUN
        [EDUPNOTRUN] = "EDUPNOTRUN",
    #endif
    #ifdef EDUPNOTWAIT
        [EDUPNOTWAIT] = "EDUPNOTWAIT",
    #endif
    #ifdef EDUPPKG
        [EDUPPKG] = "EDUPPKG",
    #endif
    #ifdef EDUPTOOMANYCPUS
        [EDUPTOOMANYCPUS] = "EDUPTOOMANYCPUS",
    #endif
    #ifdef ED_ALREADY_OPEN
        [ED_ALREADY_OPEN] = "ED_ALREADY_OPEN",
    #endif
    #ifdef ED_DEVICE_DOWN
        [ED_DEVICE_DOWN] = "ED_DEVICE_DOWN",
    #endif
    #ifdef ED_INVALID_OPERATION
        [ED_INVALID_OPERATION] = "ED_INVALID_OPERATION",
    #endif
    #ifdef ED_INVALID_RECNUM
        [ED_INVALID_RECNUM] = "ED_INVALID_RECNUM",
    #endif
    #ifdef ED_INVALID_SIZE
        [ED_INVALID_SIZE] = "ED_INVALID_SIZE",
    #endif
    #ifdef ED_IO_ERROR
        [ED_IO_ERROR] = "ED_IO_ERROR",
    #endif
    #ifdef ED_NO_MEMORY
        [ED_NO_MEMORY] = "ED_NO_MEMORY",
    #endif
    #ifdef ED_NO_SUCH_DEVICE
        [ED_NO_SUCH_DEVICE] = "ED_NO_SUCH_DEVICE",
    #endif
    #ifdef ED_READ_ONLY
        [ED_READ_ONLY] = "ED_READ_ONLY",
    #endif
    #ifdef ED_WOULD_BLOCK
        [ED_WOULD_BLOCK] = "ED_WOULD_BLOCK",
    #endif
    #ifdef EENDIAN
        [EENDIAN] = "EENDIAN",
    #endif
    #ifdef EEXIST
        [EEXIST] = "EEXIST",
    #endif
    #ifdef EFAIL
        [EFAIL] = "EFAIL",
    #endif
    #ifdef EFAULT
        [EFAULT] = "EFAULT",
    #endif
    #ifdef EFBIG
        [EFBIG] = "EFBIG",
    #endif
    #ifdef EFORMAT
        [EFORMAT] = "EFORMAT",
    #endif
    #ifdef EFPOS
        [EFPOS] = "EFPOS",
    #endif
    #ifdef EFRAGS
        [EFRAGS] = "EFRAGS",
    #endif
    #ifdef EFSCORRUPTED
        [EFSCORRUPTED] = "EFSCORRUPTED",
    #endif
    #ifdef EFTYPE
        [EFTYPE] = "EFTYPE",
    #endif
    #ifdef EGENERIC
        [EGENERIC] = "EGENERIC",
    #endif
    #ifdef EGRATUITOUS
        [EGRATUITOUS] = "EGRATUITOUS",
    #endif
    #ifdef EGRBUSY
        [EGRBUSY] = "EGRBUSY",
    #endif
    #ifdef EGREGIOUS
        [EGREGIOUS] = "EGREGIOUS",
    #endif
    #ifdef EHOSTDOWN
        [EHOSTDOWN] = "EHOSTDOWN",
    #endif
    #ifdef EHOSTNOTFOUND
        [EHOSTNOTFOUND] = "EHOSTNOTFOUND",
    #endif
    #ifdef EHOSTUNREACH
        [EHOSTUNREACH] = "EHOSTUNREACH",
    #endif
    #ifdef EHWPOISON
        [EHWPOISON] = "EHWPOISON",
    #endif
    #ifdef EIBMBADCONNECTIONMATCH
        [EIBMBADCONNECTIONMATCH] = "EIBMBADCONNECTIONMATCH",
    #endif
    #ifdef EIBMBADCONNECTIONSTATE
        [EIBMBADCONNECTIONSTATE] = "EIBMBADCONNECTIONSTATE",
    #endif
    #ifdef EIBMBADREQUESTCODE
        [EIBMBADREQUESTCODE] = "EIBMBADREQUESTCODE",
    #endif
    #ifdef EIBMBADTCPNAME
        [EIBMBADTCPNAME] = "EIBMBADTCPNAME",
    #endif
    #ifdef EIBMCALLINPROGRESS
        [EIBMCALLINPROGRESS] = "EIBMCALLINPROGRESS",
    #endif
    #ifdef EIBMCANCELLED
        [EIBMCANCELLED] = "EIBMCANCELLED",
    #endif
    #ifdef EIBMCONFLICT
        [EIBMCONFLICT] = "EIBMCONFLICT",
    #endif
    #ifdef EIBMINVDELETE
        [EIBMINVDELETE] = "EIBMINVDELETE",
    #endif
    #ifdef EIBMINVSOCKET
        [EIBMINVSOCKET] = "EIBMINVSOCKET",
    #endif
    #ifdef EIBMINVTCPCONNECTION
        [EIBMINVTCPCONNECTION] = "EIBMINVTCPCONNECTION",
    #endif
    #ifdef EIBMINVTSRBUSERDATA
        [EIBMINVTSRBUSERDATA] = "EIBMINVTSRBUSERDATA",
    #endif
    #ifdef EIBMINVUSERDATA
        [EIBMINVUSERDATA] = "EIBMINVUSERDATA",
    #endif
    #ifdef EIBMIUCVERR
        [EIBMIUCVERR] = "EIBMIUCVERR",
    #endif
    #ifdef EIBMNOACTIVETCP
        [EIBMNOACTIVETCP] = "EIBMNOACTIVETCP",
    #endif
    #ifdef EIBMSELECTEXPOST
        [EIBMSELECTEXPOST] = "EIBMSELECTEXPOST",
    #endif
    #ifdef EIBMSOCKINUSE
        [EIBMSOCKINUSE] = "EIBMSOCKINUSE",
    #endif
    #ifdef EIBMSOCKOUTOFRANGE
        [EIBMSOCKOUTOFRANGE] = "EIBMSOCKOUTOFRANGE",
    #endif
    #ifdef EIBMTCPABEND
        [EIBMTCPABEND] = "EIBMTCPABEND",
    #endif
    #ifdef EIBMTERMERROR
        [EIBMTERMERROR] = "EIBMTERMERROR",
    #endif
    #ifdef EIBMUNAUTHORIZEDCALLER
        [EIBMUNAUTHORIZEDCALLER] = "EIBMUNAUTHORIZEDCALLER",
    #endif
    #ifdef EIDRM
        [EIDRM] = "EIDRM",
    #endif
    #ifdef EIEIO
        [EIEIO] = "EIEIO",
    #endif
    #ifdef EILSEQ
        [EILSEQ] = "EILSEQ",
    #endif
    #ifdef EINIT
        [EINIT] = "EINIT",
    #endif
    #ifdef EINODETABLEFULL
        [EINODETABLEFULL] = "EINODETABLEFULL",
    #endif
    #ifdef EINPROG
        #if !defined(EINPROGRESS) || EINPROG != EINPROGRESS
        [EINPROG] = "EINPROG",
        #endif
    #endif
    #ifdef EINPROGRESS
        [EINPROGRESS] = "EINPROGRESS",
    #endif
    #ifdef EINTEGRITY
        [EINTEGRITY] = "EINTEGRITY",
    #endif
    #ifdef EINTR
        [EINTR] = "EINTR",
    #endif
    #ifdef EINTRNODATA
        [EINTRNODATA] = "EINTRNODATA",
    #endif
    #ifdef EINVAL
        [EINVAL] = "EINVAL",
    #endif
    #ifdef EINVALIDCLIENTID
        [EINVALIDCLIENTID] = "EINVALIDCLIENTID",
    #endif
    #ifdef EINVALIDCOMBINATION
        [EINVALIDCOMBINATION] = "EINVALIDCOMBINATION",
    #endif
    #ifdef EINVALIDNAME
        [EINVALIDNAME] = "EINVALIDNAME",
    #endif
    #ifdef EINVALIDRXSOCKETCALL
        [EINVALIDRXSOCKETCALL] = "EINVALIDRXSOCKETCALL",
    #endif
    #ifdef EIO
        [EIO] = "EIO",
    #endif
    #ifdef EIOCBQUEUED
        [EIOCBQUEUED] = "EIOCBQUEUED",
    #endif
    #ifdef EIOCBRETRY
        [EIOCBRETRY] = "EIOCBRETRY",
    #endif
    #ifdef EIORESID
        [EIORESID] = "EIORESID",
    #endif
    #ifdef EIPADDRNOTFOUND
        [EIPADDRNOTFOUND] = "EIPADDRNOTFOUND",
    #endif
    #ifdef EIPSEC
        [EIPSEC] = "EIPSEC",
    #endif
    #ifdef EISCONN
        [EISCONN] = "EISCONN",
    #endif
    #ifdef EISDIR
        [EISDIR] = "EISDIR",
    #endif
    #ifdef EISNAM
        [EISNAM] = "EISNAM",
    #endif
    #ifdef EJUKEBOX
        [EJUKEBOX] = "EJUKEBOX",
    #endif
    #ifdef EJUSTRETURN
        [EJUSTRETURN] = "EJUSTRETURN",
    #endif
    #ifdef EKEEPLOOKING
        [EKEEPLOOKING] = "EKEEPLOOKING",
    #endif
    #ifdef EKERN_ABORTED
        [EKERN_ABORTED] = "EKERN_ABORTED",
    #endif
    #ifdef EKERN_FAILURE
        [EKERN_FAILURE] = "EKERN_FAILURE",
    #endif
    #ifdef EKERN_INTERRUPTED
        [EKERN_INTERRUPTED] = "EKERN_INTERRUPTED",
    #endif
    #ifdef EKERN_INVALID_ADDRESS
        [EKERN_INVALID_ADDRESS] = "EKERN_INVALID_ADDRESS",
    #endif
    #ifdef EKERN_INVALID_ARGUMENT
        [EKERN_INVALID_ARGUMENT] = "EKERN_INVALID_ARGUMENT",
    #endif
    #ifdef EKERN_INVALID_CAPABILITY
        [EKERN_INVALID_CAPABILITY] = "EKERN_INVALID_CAPABILITY",
    #endif
    #ifdef EKERN_INVALID_HOST
        [EKERN_INVALID_HOST] = "EKERN_INVALID_HOST",
    #endif
    #ifdef EKERN_INVALID_NAME
        [EKERN_INVALID_NAME] = "EKERN_INVALID_NAME",
    #endif
    #ifdef EKERN_INVALID_RIGHT
        [EKERN_INVALID_RIGHT] = "EKERN_INVALID_RIGHT",
    #endif
    #ifdef EKERN_INVALID_TASK
        [EKERN_INVALID_TASK] = "EKERN_INVALID_TASK",
    #endif
    #ifdef EKERN_INVALID_VALUE
        [EKERN_INVALID_VALUE] = "EKERN_INVALID_VALUE",
    #endif
    #ifdef EKERN_MEMORY_ERROR
        [EKERN_MEMORY_ERROR] = "EKERN_MEMORY_ERROR",
    #endif
    #ifdef EKERN_MEMORY_FAILURE
        [EKERN_MEMORY_FAILURE] = "EKERN_MEMORY_FAILURE",
    #endif
    #ifdef EKERN_MEMORY_PRESENT
        [EKERN_MEMORY_PRESENT] = "EKERN_MEMORY_PRESENT",
    #endif
    #ifdef EKERN_NAME_EXISTS
        [EKERN_NAME_EXISTS] = "EKERN_NAME_EXISTS",
    #endif
    #ifdef EKERN_NOT_IN_SET
        [EKERN_NOT_IN_SET] = "EKERN_NOT_IN_SET",
    #endif
    #ifdef EKERN_NOT_RECEIVER
        [EKERN_NOT_RECEIVER] = "EKERN_NOT_RECEIVER",
    #endif
    #ifdef EKERN_NO_ACCESS
        [EKERN_NO_ACCESS] = "EKERN_NO_ACCESS",
    #endif
    #ifdef EKERN_NO_SPACE
        [EKERN_NO_SPACE] = "EKERN_NO_SPACE",
    #endif
    #ifdef EKERN_PROTECTION_FAILURE
        [EKERN_PROTECTION_FAILURE] = "EKERN_PROTECTION_FAILURE",
    #endif
    #ifdef EKERN_RESOURCE_SHORTAGE
        [EKERN_RESOURCE_SHORTAGE] = "EKERN_RESOURCE_SHORTAGE",
    #endif
    #ifdef EKERN_RIGHT_EXISTS
        [EKERN_RIGHT_EXISTS] = "EKERN_RIGHT_EXISTS",
    #endif
    #ifdef EKERN_TERMINATED
        [EKERN_TERMINATED] = "EKERN_TERMINATED",
    #endif
    #ifdef EKERN_TIMEDOUT
        [EKERN_TIMEDOUT] = "EKERN_TIMEDOUT",
    #endif
    #ifdef EKERN_UREFS_OVERFLOW
        [EKERN_UREFS_OVERFLOW] = "EKERN_UREFS_OVERFLOW",
    #endif
    #ifdef EKERN_WRITE_PROTECTION_FAILURE
        [EKERN_WRITE_PROTECTION_FAILURE] = "EKERN_WRITE_PROTECTION_FAILURE",
    #endif
    #ifdef EKEYEXPIRED
        [EKEYEXPIRED] = "EKEYEXPIRED",
    #endif
    #ifdef EKEYREJECTED
        [EKEYREJECTED] = "EKEYREJECTED",
    #endif
    #ifdef EKEYREVOKED
        [EKEYREVOKED] = "EKEYREVOKED",
    #endif
    #ifdef EL2HLT
        [EL2HLT] = "EL2HLT",
    #endif
    #ifdef EL2NSYNC
        [EL2NSYNC] = "EL2NSYNC",
    #endif
    #ifdef EL3HLT
        [EL3HLT] = "EL3HLT",
    #endif
    #ifdef EL3RST
        [EL3RST] = "EL3RST",
    #endif
    #ifdef ELBIN
        [ELBIN] = "ELBIN",
    #endif
    #ifdef ELIBACC
        [ELIBACC] = "ELIBACC",
    #endif
    #ifdef ELIBBAD
        [ELIBBAD] = "ELIBBAD",
    #endif
    #ifdef ELIBEXEC
        [ELIBEXEC] = "ELIBEXEC",
    #endif
    #ifdef ELIBMAX
        [ELIBMAX] = "ELIBMAX",
    #endif
    #ifdef ELIBSCN
        [ELIBSCN] = "ELIBSCN",
    #endif
    #ifdef ELINKED
        [ELINKED] = "ELINKED",
    #endif
    #ifdef ELNRNG
        [ELNRNG] = "ELNRNG",
    #endif
    #ifdef ELOCKED
        [ELOCKED] = "ELOCKED",
    #endif
    #ifdef ELOCKUNMAPPED
        [ELOCKUNMAPPED] = "ELOCKUNMAPPED",
    #endif
    #ifdef ELOOP
        [ELOOP] = "ELOOP",
    #endif
    #ifdef EMACH_RCV_BODY_ERROR
        [EMACH_RCV_BODY_ERROR] = "EMACH_RCV_BODY_ERROR",
    #endif
    #ifdef EMACH_RCV_HEADER_ERROR
        [EMACH_RCV_HEADER_ERROR] = "EMACH_RCV_HEADER_ERROR",
    #endif
    #ifdef EMACH_RCV_INTERRUPTED
        [EMACH_RCV_INTERRUPTED] = "EMACH_RCV_INTERRUPTED",
    #endif
    #ifdef EMACH_RCV_INVALID_DATA
        [EMACH_RCV_INVALID_DATA] = "EMACH_RCV_INVALID_DATA",
    #endif
    #ifdef EMACH_RCV_INVALID_NAME
        [EMACH_RCV_INVALID_NAME] = "EMACH_RCV_INVALID_NAME",
    #endif
    #ifdef EMACH_RCV_INVALID_NOTIFY
        [EMACH_RCV_INVALID_NOTIFY] = "EMACH_RCV_INVALID_NOTIFY",
    #endif
    #ifdef EMACH_RCV_IN_PROGRESS
        [EMACH_RCV_IN_PROGRESS] = "EMACH_RCV_IN_PROGRESS",
    #endif
    #ifdef EMACH_RCV_IN_SET
        [EMACH_RCV_IN_SET] = "EMACH_RCV_IN_SET",
    #endif
    #ifdef EMACH_RCV_PORT_CHANGED
        [EMACH_RCV_PORT_CHANGED] = "EMACH_RCV_PORT_CHANGED",
    #endif
    #ifdef EMACH_RCV_PORT_DIED
        [EMACH_RCV_PORT_DIED] = "EMACH_RCV_PORT_DIED",
    #endif
    #ifdef EMACH_RCV_TIMED_OUT
        [EMACH_RCV_TIMED_OUT] = "EMACH_RCV_TIMED_OUT",
    #endif
    #ifdef EMACH_RCV_TOO_LARGE
        [EMACH_RCV_TOO_LARGE] = "EMACH_RCV_TOO_LARGE",
    #endif
    #ifdef EMACH_SEND_INTERRUPTED
        [EMACH_SEND_INTERRUPTED] = "EMACH_SEND_INTERRUPTED",
    #endif
    #ifdef EMACH_SEND_INVALID_DATA
        [EMACH_SEND_INVALID_DATA] = "EMACH_SEND_INVALID_DATA",
    #endif
    #ifdef EMACH_SEND_INVALID_DEST
        [EMACH_SEND_INVALID_DEST] = "EMACH_SEND_INVALID_DEST",
    #endif
    #ifdef EMACH_SEND_INVALID_HEADER
        [EMACH_SEND_INVALID_HEADER] = "EMACH_SEND_INVALID_HEADER",
    #endif
    #ifdef EMACH_SEND_INVALID_MEMORY
        [EMACH_SEND_INVALID_MEMORY] = "EMACH_SEND_INVALID_MEMORY",
    #endif
    #ifdef EMACH_SEND_INVALID_NOTIFY
        [EMACH_SEND_INVALID_NOTIFY] = "EMACH_SEND_INVALID_NOTIFY",
    #endif
    #ifdef EMACH_SEND_INVALID_REPLY
        [EMACH_SEND_INVALID_REPLY] = "EMACH_SEND_INVALID_REPLY",
    #endif
    #ifdef EMACH_SEND_INVALID_RIGHT
        [EMACH_SEND_INVALID_RIGHT] = "EMACH_SEND_INVALID_RIGHT",
    #endif
    #ifdef EMACH_SEND_INVALID_TYPE
        [EMACH_SEND_INVALID_TYPE] = "EMACH_SEND_INVALID_TYPE",
    #endif
    #ifdef EMACH_SEND_IN_PROGRESS
        [EMACH_SEND_IN_PROGRESS] = "EMACH_SEND_IN_PROGRESS",
    #endif
    #ifdef EMACH_SEND_MSG_TOO_SMALL
        [EMACH_SEND_MSG_TOO_SMALL] = "EMACH_SEND_MSG_TOO_SMALL",
    #endif
    #ifdef EMACH_SEND_NOTIFY_IN_PROGRESS
        [EMACH_SEND_NOTIFY_IN_PROGRESS] = "EMACH_SEND_NOTIFY_IN_PROGRESS",
    #endif
    #ifdef EMACH_SEND_NO_BUFFER
        [EMACH_SEND_NO_BUFFER] = "EMACH_SEND_NO_BUFFER",
    #endif
    #ifdef EMACH_SEND_NO_NOTIFY
        [EMACH_SEND_NO_NOTIFY] = "EMACH_SEND_NO_NOTIFY",
    #endif
    #ifdef EMACH_SEND_TIMED_OUT
        [EMACH_SEND_TIMED_OUT] = "EMACH_SEND_TIMED_OUT",
    #endif
    #ifdef EMACH_SEND_WILL_NOTIFY
        [EMACH_SEND_WILL_NOTIFY] = "EMACH_SEND_WILL_NOTIFY",
    #endif
    #ifdef EMAXSOCKETSREACHED
        [EMAXSOCKETSREACHED] = "EMAXSOCKETSREACHED",
    #endif
    #ifdef EMEDIA
        [EMEDIA] = "EMEDIA",
    #endif
    #ifdef EMEDIUMTYPE
        [EMEDIUMTYPE] = "EMEDIUMTYPE",
    #endif
    #ifdef EMFILE
        [EMFILE] = "EMFILE",
    #endif
    #ifdef EMIG_ARRAY_TOO_LARGE
        [EMIG_ARRAY_TOO_LARGE] = "EMIG_ARRAY_TOO_LARGE",
    #endif
    #ifdef EMIG_BAD_ARGUMENTS
        [EMIG_BAD_ARGUMENTS] = "EMIG_BAD_ARGUMENTS",
    #endif
    #ifdef EMIG_BAD_ID
        [EMIG_BAD_ID] = "EMIG_BAD_ID",
    #endif
    #ifdef EMIG_DESTROY_REQUEST
        [EMIG_DESTROY_REQUEST] = "EMIG_DESTROY_REQUEST",
    #endif
    #ifdef EMIG_EXCEPTION
        [EMIG_EXCEPTION] = "EMIG_EXCEPTION",
    #endif
    #ifdef EMIG_NO_REPLY
        [EMIG_NO_REPLY] = "EMIG_NO_REPLY",
    #endif
    #ifdef EMIG_REMOTE_ERROR
        [EMIG_REMOTE_ERROR] = "EMIG_REMOTE_ERROR",
    #endif
    #ifdef EMIG_REPLY_MISMATCH
        [EMIG_REPLY_MISMATCH] = "EMIG_REPLY_MISMATCH",
    #endif
    #ifdef EMIG_SERVER_DIED
        [EMIG_SERVER_DIED] = "EMIG_SERVER_DIED",
    #endif
    #ifdef EMIG_TYPE_ERROR
        [EMIG_TYPE_ERROR] = "EMIG_TYPE_ERROR",
    #endif
    #ifdef EMISSED
        [EMISSED] = "EMISSED",
    #endif
    #ifdef EMLINK
        [EMLINK] = "EMLINK",
    #endif
    #ifdef EMORE
        [EMORE] = "EMORE",
    #endif
    #ifdef EMOUNTEXIT
        [EMOUNTEXIT] = "EMOUNTEXIT",
    #endif
    #ifdef EMOVEFD
        [EMOVEFD] = "EMOVEFD",
    #endif
    #ifdef EMSGSIZE
        [EMSGSIZE] = "EMSGSIZE",
    #endif
    #ifdef EMTIMERS
        [EMTIMERS] = "EMTIMERS",
    #endif
    #ifdef EMULTIHOP
        [EMULTIHOP] = "EMULTIHOP",
    #endif
    #ifdef EMVSARMERROR
        [EMVSARMERROR] = "EMVSARMERROR",
    #endif
    #ifdef EMVSCATLG
        [EMVSCATLG] = "EMVSCATLG",
    #endif
    #ifdef EMVSCPLERROR
        [EMVSCPLERROR] = "EMVSCPLERROR",
    #endif
    #ifdef EMVSCVAF
        [EMVSCVAF] = "EMVSCVAF",
    #endif
    #ifdef EMVSDYNALC
        [EMVSDYNALC] = "EMVSDYNALC",
    #endif
    #ifdef EMVSERR
        [EMVSERR] = "EMVSERR",
    #endif
    #ifdef EMVSEXPIRE
        [EMVSEXPIRE] = "EMVSEXPIRE",
    #endif
    #ifdef EMVSINITIAL
        [EMVSINITIAL] = "EMVSINITIAL",
    #endif
    #ifdef EMVSNORTL
        [EMVSNORTL] = "EMVSNORTL",
    #endif
    #ifdef EMVSNOTUP
        [EMVSNOTUP] = "EMVSNOTUP",
    #endif
    #ifdef EMVSPARM
        [EMVSPARM] = "EMVSPARM",
    #endif
    #ifdef EMVSPASSWORD
        [EMVSPASSWORD] = "EMVSPASSWORD",
    #endif
    #ifdef EMVSPFSFILE
        [EMVSPFSFILE] = "EMVSPFSFILE",
    #endif
    #ifdef EMVSPFSPERM
        [EMVSPFSPERM] = "EMVSPFSPERM",
    #endif
    #ifdef EMVSSAF2ERR
        [EMVSSAF2ERR] = "EMVSSAF2ERR",
    #endif
    #ifdef EMVSSAFEXTRERR
        [EMVSSAFEXTRERR] = "EMVSSAFEXTRERR",
    #endif
    #ifdef EMVSWLMERROR
        [EMVSWLMERROR] = "EMVSWLMERROR",
    #endif
    #ifdef ENAMETOOLONG
        [ENAMETOOLONG] = "ENAMETOOLONG",
    #endif
    #ifdef ENAVAIL
        [ENAVAIL] = "ENAVAIL",
    #endif
    #ifdef ENEEDAUTH
        [ENEEDAUTH] = "ENEEDAUTH",
    #endif
    #ifdef ENETDOWN
        [ENETDOWN] = "ENETDOWN",
    #endif
    #ifdef ENETRESET
        [ENETRESET] = "ENETRESET",
    #endif
    #ifdef ENETUNREACH
        [ENETUNREACH] = "ENETUNREACH",
    #endif
    #ifdef ENFILE
        [ENFILE] = "ENFILE",
    #endif
    #ifdef ENFSREMOTE
        [ENFSREMOTE] = "ENFSREMOTE",
    #endif
    #ifdef ENIVALIDFILENAME
        [ENIVALIDFILENAME] = "ENIVALIDFILENAME",
    #endif
    #ifdef ENMELONG
        [ENMELONG] = "ENMELONG",
    #endif
    #ifdef ENMFILE
        [ENMFILE] = "ENMFILE",
    #endif
    #ifdef ENOACTIVE
        [ENOACTIVE] = "ENOACTIVE",
    #endif
    #ifdef ENOANO
        [ENOANO] = "ENOANO",
    #endif
    #ifdef ENOATTR
        [ENOATTR] = "ENOATTR",
    #endif
    #ifdef ENOBUFS
        [ENOBUFS] = "ENOBUFS",
    #endif
    #ifdef ENOCONN
        [ENOCONN] = "ENOCONN",
    #endif
    #ifdef ENOCONNECT
        [ENOCONNECT] = "ENOCONNECT",
    #endif
    #ifdef ENOCSI
        [ENOCSI] = "ENOCSI",
    #endif
    #ifdef ENODATA
        [ENODATA] = "ENODATA",
    #endif
    #ifdef ENODEV
        [ENODEV] = "ENODEV",
    #endif
    #ifdef ENODUST
        [ENODUST] = "ENODUST",
    #endif
    #ifdef ENOENT
        [ENOENT] = "ENOENT",
    #endif
    #ifdef ENOEXEC
        [ENOEXEC] = "ENOEXEC",
    #endif
    #ifdef ENOFPA
        [ENOFPA] = "ENOFPA",
    #endif
    #ifdef ENOGR
        [ENOGR] = "ENOGR",
    #endif
    #ifdef ENOGRACE
        [ENOGRACE] = "ENOGRACE",
    #endif
    #ifdef ENOIOCTL
        [ENOIOCTL] = "ENOIOCTL",
    #endif
    #ifdef ENOIOCTLCMD
        [ENOIOCTLCMD] = "ENOIOCTLCMD",
    #endif
    #ifdef ENOKEY
        [ENOKEY] = "ENOKEY",
    #endif
    #ifdef ENOLCK
        [ENOLCK] = "ENOLCK",
    #endif
    #ifdef ENOLIC
        [ENOLIC] = "ENOLIC",
    #endif
    #ifdef ENOLINK
        [ENOLINK] = "ENOLINK",
    #endif
    #ifdef ENOLOAD
        [ENOLOAD] = "ENOLOAD",
    #endif
    #ifdef ENOMATCH
        [ENOMATCH] = "ENOMATCH",
    #endif
    #ifdef ENOMEDIUM
        [ENOMEDIUM] = "ENOMEDIUM",
    #endif
    #ifdef ENOMEM
        [ENOMEM] = "ENOMEM",
    #endif
    #ifdef ENOMOVE
        [ENOMOVE] = "ENOMOVE",
    #endif
    #ifdef ENOMSG
        [ENOMSG] = "ENOMSG",
    #endif
    #ifdef ENONDP
        [ENONDP] = "ENONDP",
    #endif
    #ifdef ENONET
        [ENONET] = "ENONET",
    #endif
    #ifdef ENOPARAM
        [ENOPARAM] = "ENOPARAM",
    #endif
    #ifdef ENOPARTNERINFO
        [ENOPARTNERINFO] = "ENOPARTNERINFO",
    #endif
    #ifdef ENOPKG
        [ENOPKG] = "ENOPKG",
    #endif
    #ifdef ENOPOLICY
        [ENOPOLICY] = "ENOPOLICY",
    #endif
    #ifdef ENOPROTOOPT
        [ENOPROTOOPT] = "ENOPROTOOPT",
    #endif
    #ifdef ENOREG
        [ENOREG] = "ENOREG",
    #endif
    #ifdef ENOREMOTE
        [ENOREMOTE] = "ENOREMOTE",
    #endif
    #ifdef ENORESOURCES
        [ENORESOURCES] = "ENORESOURCES",
    #endif
    #ifdef ENOREUSE
        [ENOREUSE] = "ENOREUSE",
    #endif
    #ifdef ENOSHARE
        [ENOSHARE] = "ENOSHARE",
    #endif
    #ifdef ENOSPC
        [ENOSPC] = "ENOSPC",
    #endif
    #ifdef ENOSR
        [ENOSR] = "ENOSR",
    #endif
    #ifdef ENOSTR
        [ENOSTR] = "ENOSTR",
    #endif
    #ifdef ENOSYM
        [ENOSYM] = "ENOSYM",
    #endif
    #ifdef ENOSYS
        [ENOSYS] = "ENOSYS",
    #endif
    #ifdef ENOSYSTEM
        [ENOSYSTEM] = "ENOSYSTEM",
    #endif
    #ifdef ENOTACTIVE
        [ENOTACTIVE] = "ENOTACTIVE",
    #endif
    #ifdef ENOTAUTH
        [ENOTAUTH] = "ENOTAUTH",
    #endif
    #ifdef ENOTBLK
        [ENOTBLK] = "ENOTBLK",
    #endif
    #ifdef ENOTCAPABLE
        [ENOTCAPABLE] = "ENOTCAPABLE",
    #endif
    #ifdef ENOTCONN
        [ENOTCONN] = "ENOTCONN",
    #endif
    #ifdef ENOTDIR
        [ENOTDIR] = "ENOTDIR",
    #endif
    #ifdef ENOTEMPT
        [ENOTEMPT] = "ENOTEMPT",
    #endif
    #ifdef ENOTEMPTY
        [ENOTEMPTY] = "ENOTEMPTY",
    #endif
    #ifdef ENOTNAM
        [ENOTNAM] = "ENOTNAM",
    #endif
    #ifdef ENOTREADY
        [ENOTREADY] = "ENOTREADY",
    #endif
    #ifdef ENOTRECOVERABLE
        [ENOTRECOVERABLE] = "ENOTRECOVERABLE",
    #endif
    #ifdef ENOTRUST
        [ENOTRUST] = "ENOTRUST",
    #endif
    #ifdef ENOTSOCK
        [ENOTSOCK] = "ENOTSOCK",
    #endif
    #ifdef ENOTSUP
        [ENOTSUP] = "ENOTSUP",
    #endif
    #ifdef ENOTSUPP
        [ENOTSUPP] = "ENOTSUPP",
    #endif
    #ifdef ENOTSYNC
        [ENOTSYNC] = "ENOTSYNC",
    #endif
    #ifdef ENOTTY
        [ENOTTY] = "ENOTTY",
    #endif
    #ifdef ENOTUNIQ
        [ENOTUNIQ] = "ENOTUNIQ",
    #endif
    #ifdef ENOUNLD
        [ENOUNLD] = "ENOUNLD",
    #endif
    #ifdef ENOUNREG
        [ENOUNREG] = "ENOUNREG",
    #endif
    #ifdef ENOURG
        [ENOURG] = "ENOURG",
    #endif
    #ifdef ENXIO
        [ENXIO] = "ENXIO",
    #endif
    #ifdef EOFFLOADboxDOWN
        [EOFFLOADboxDOWN] = "EOFFLOADboxDOWN",
    #endif
    #ifdef EOFFLOADboxERROR
        [EOFFLOADboxERROR] = "EOFFLOADboxERROR",
    #endif
    #ifdef EOFFLOADboxRESTART
        [EOFFLOADboxRESTART] = "EOFFLOADboxRESTART",
    #endif
    #ifdef EOPCOMPLETE
        [EOPCOMPLETE] = "EOPCOMPLETE",
    #endif
    #ifdef EOPENSTALE
        [EOPENSTALE] = "EOPENSTALE",
    #endif
    #ifdef EOPNOTSUPP
        #if !defined(ENOTSUP) || EOPNOTSUPP != ENOTSUP
        [EOPNOTSUPP] = "EOPNOTSUPP",
        #endif
    #endif
    #ifdef EOUTOFSTATE
        [EOUTOFSTATE] = "EOUTOFSTATE",
    #endif
    #ifdef EOVERFLOW
        [EOVERFLOW] = "EOVERFLOW",
    #endif
    #ifdef EOWNERDEAD
        [EOWNERDEAD] = "EOWNERDEAD",
    #endif
    #ifdef EPACKSIZE
        [EPACKSIZE] = "EPACKSIZE",
    #endif
    #ifdef EPASSTHROUGH
        [EPASSTHROUGH] = "EPASSTHROUGH",
    #endif
    #ifdef EPATHREMOTE
        [EPATHREMOTE] = "EPATHREMOTE",
    #endif
    #ifdef EPERM
        [EPERM] = "EPERM",
    #endif
    #ifdef EPFNOSUPPORT
        [EPFNOSUPPORT] = "EPFNOSUPPORT",
    #endif
    #ifdef EPIPE
        [EPIPE] = "EPIPE",
    #endif
    #ifdef EPOWERF
        [EPOWERF] = "EPOWERF",
    #endif
    #ifdef EPROBE_DEFER
        [EPROBE_DEFER] = "EPROBE_DEFER",
    #endif
    #ifdef EPROCLIM
        [EPROCLIM] = "EPROCLIM",
    #endif
    #ifdef EPROCUNAVAIL
        [EPROCUNAVAIL] = "EPROCUNAVAIL",
    #endif
    #ifdef EPROGMISMATCH
        [EPROGMISMATCH] = "EPROGMISMATCH",
    #endif
    #ifdef EPROGUNAVAIL
        [EPROGUNAVAIL] = "EPROGUNAVAIL",
    #endif
    #ifdef EPROTO
        [EPROTO] = "EPROTO",
    #endif
    #ifdef EPROTONOSUPPORT
        [EPROTONOSUPPORT] = "EPROTONOSUPPORT",
    #endif
    #ifdef EPROTOTYPE
        [EPROTOTYPE] = "EPROTOTYPE",
    #endif
    #ifdef EPWROFF
        [EPWROFF] = "EPWROFF",
    #endif
    #ifdef EQFULL
        [EQFULL] = "EQFULL",
    #endif
    #ifdef EQSUSPENDED
        [EQSUSPENDED] = "EQSUSPENDED",
    #endif
    #ifdef ERANGE
        [ERANGE] = "ERANGE",
    #endif
    #ifdef ERECALLCONFLICT
        [ERECALLCONFLICT] = "ERECALLCONFLICT",
    #endif
    #ifdef ERECURSE
        [ERECURSE] = "ERECURSE",
    #endif
    #ifdef ERECYCLE
        [ERECYCLE] = "ERECYCLE",
    #endif
    #ifdef EREDRIVEOPEN
        [EREDRIVEOPEN] = "EREDRIVEOPEN",
    #endif
    #ifdef EREFUSED
        #if !defined(ECONNREFUSED) || EREFUSED != ECONNREFUSED
        [EREFUSED] = "EREFUSED",
        #endif
    #endif
    #ifdef ERELOC
        [ERELOC] = "ERELOC",
    #endif
    #ifdef ERELOCATED
        [ERELOCATED] = "ERELOCATED",
    #endif
    #ifdef ERELOOKUP
        [ERELOOKUP] = "ERELOOKUP",
    #endif
    #ifdef EREMCHG
        [EREMCHG] = "EREMCHG",
    #endif
    #ifdef EREMDEV
        [EREMDEV] = "EREMDEV",
    #endif
    #ifdef EREMOTE
        [EREMOTE] = "EREMOTE",
    #endif
    #ifdef EREMOTEIO
        [EREMOTEIO] = "EREMOTEIO",
    #endif
    #ifdef EREMOTERELEASE
        [EREMOTERELEASE] = "EREMOTERELEASE",
    #endif
    #ifdef ERESTART
        [ERESTART] = "ERESTART",
    #endif
    #ifdef ERESTARTNOHAND
        [ERESTARTNOHAND] = "ERESTARTNOHAND",
    #endif
    #ifdef ERESTARTNOINTR
        [ERESTARTNOINTR] = "ERESTARTNOINTR",
    #endif
    #ifdef ERESTARTSYS
        [ERESTARTSYS] = "ERESTARTSYS",
    #endif
    #ifdef ERESTART_RESTARTBLOCK
        [ERESTART_RESTARTBLOCK] = "ERESTART_RESTARTBLOCK",
    #endif
    #ifdef ERFKILL
        [ERFKILL] = "ERFKILL",
    #endif
    #ifdef EROFS
        [EROFS] = "EROFS",
    #endif
    #ifdef ERPCMISMATCH
        [ERPCMISMATCH] = "ERPCMISMATCH",
    #endif
    #ifdef ERREMOTE
        [ERREMOTE] = "ERREMOTE",
    #endif
    #ifdef ESAD
        [ESAD] = "ESAD",
    #endif
    #ifdef ESECTYPEINVAL
        [ESECTYPEINVAL] = "ESECTYPEINVAL",
    #endif
    #ifdef ESERVERFAULT
        [ESERVERFAULT] = "ESERVERFAULT",
    #endif
    #ifdef ESHLIBVERS
        [ESHLIBVERS] = "ESHLIBVERS",
    #endif
    #ifdef ESHUTDOWN
        [ESHUTDOWN] = "ESHUTDOWN",
    #endif
    #ifdef ESIGPARM
        [ESIGPARM] = "ESIGPARM",
    #endif
    #ifdef ESOCKETNOTALLOCATED
        [ESOCKETNOTALLOCATED] = "ESOCKETNOTALLOCATED",
    #endif
    #ifdef ESOCKETNOTDEFINED
        [ESOCKETNOTDEFINED] = "ESOCKETNOTDEFINED",
    #endif
    #ifdef ESOCKTNOSUPPORT
        [ESOCKTNOSUPPORT] = "ESOCKTNOSUPPORT",
    #endif
    #ifdef ESOFT
        [ESOFT] = "ESOFT",
    #endif
    #ifdef ESPIPE
        [ESPIPE] = "ESPIPE",
    #endif
    #ifdef ESRCH
        [ESRCH] = "ESRCH",
    #endif
    #ifdef ESRMNT
        [ESRMNT] = "ESRMNT",
    #endif
    #ifdef ESRVRFAULT
        [ESRVRFAULT] = "ESRVRFAULT",
    #endif
    #ifdef ESTALE
        [ESTALE] = "ESTALE",
    #endif
    #ifdef ESTRPIPE
        [ESTRPIPE] = "ESTRPIPE",
    #endif
    #ifdef ESUBTASKALREADYACTIVE
        [ESUBTASKALREADYACTIVE] = "ESUBTASKALREADYACTIVE",
    #endif
    #ifdef ESUBTASKINVALID
        [ESUBTASKINVALID] = "ESUBTASKINVALID",
    #endif
    #ifdef ESUBTASKNOTACTIVE
        [ESUBTASKNOTACTIVE] = "ESUBTASKNOTACTIVE",
    #endif
    #ifdef ESYSERROR
        [ESYSERROR] = "ESYSERROR",
    #endif
    #ifdef ETERM
        [ETERM] = "ETERM",
    #endif
    #ifdef ETEXTABLEFULL
        [ETEXTABLEFULL] = "ETEXTABLEFULL",
    #endif
    #ifdef ETIME
        [ETIME] = "ETIME",
    #endif
    #ifdef ETIMEDOUT
        [ETIMEDOUT] = "ETIMEDOUT",
    #endif
    #ifdef ETOOMANYREFS
        [ETOOMANYREFS] = "ETOOMANYREFS",
    #endif
    #ifdef ETOOSMALL
        [ETOOSMALL] = "ETOOSMALL",
    #endif
    #ifdef ETRAPDENIED
        [ETRAPDENIED] = "ETRAPDENIED",
    #endif
    #ifdef ETXTBSY
        [ETXTBSY] = "ETXTBSY",
    #endif
    #ifdef ETcpBadObj
        [ETcpBadObj] = "ETcpBadObj",
    #endif
    #ifdef ETcpClosed
        [ETcpClosed] = "ETcpClosed",
    #endif
    #ifdef ETcpErr
        [ETcpErr] = "ETcpErr",
    #endif
    #ifdef ETcpLinked
        [ETcpLinked] = "ETcpLinked",
    #endif
    #ifdef ETcpOutOfState
        [ETcpOutOfState] = "ETcpOutOfState",
    #endif
    #ifdef ETcpUnattach
        [ETcpUnattach] = "ETcpUnattach",
    #endif
    #ifdef EUCLEAN
        [EUCLEAN] = "EUCLEAN",
    #endif
    #ifdef EUNATCH
        [EUNATCH] = "EUNATCH",
    #endif
    #ifdef EUNKNOWN
        [EUNKNOWN] = "EUNKNOWN",
    #endif
    #ifdef EURG
        [EURG] = "EURG",
    #endif
    #ifdef EUSERS
        [EUSERS] = "EUSERS",
    #endif
    #ifdef EVERSION
        [EVERSION] = "EVERSION",
    #endif
    #ifdef EWOULDBLOCK
        #if !defined(EAGAIN) || EWOULDBLOCK != EAGAIN
        [EWOULDBLOCK] = "EWOULDBLOCK",
        #endif
    #endif
    #ifdef EWRONGFS
        [EWRONGFS] = "EWRONGFS",
    #endif
    #ifdef EWRPROTECT
        [EWRPROTECT] = "EWRPROTECT",
    #endif
    #ifdef EXDEV
        [EXDEV] = "EXDEV",
    #endif
    #ifdef EXFULL
        [EXFULL] = "EXFULL",
    #endif
